"""empty message

Revision ID: 31375eee8ccf
Revises: 1c7f5a209426
Create Date: 2023-08-28 15:21:15.184203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31375eee8ccf'
down_revision = '1c7f5a209426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
